#include <string>
#include <fstream>
#include <iostream>
#include <vector>
#include <iomanip>
#include <sstream>
//h
using namespace std;
int main()
{
	cout << "Star Conflict Log Filter.\n";
	cout << "v 0.02b  12/5/2019\nby ComwpODG\n\n";
	string filename;
	string sterms;
	cout << "File name: ";
	cin >> filename;
	ifstream infile(filename);
	cout << "\nOutput file name: ";
	string outf;
	cin >> outf;
	ofstream outfile(outf);
	cout << "\nList the terms you wish to choose to include to preserve in the filter:\n";
	cout << "\tIf a line has this in it, it will be preserved, otherwise thrown out.\n";
	cout << "\tTo just select messages sent by a certain user, use brackets such as [name].\n";
	cout << "\tUse a comma to separate values, addding multiple search terms for the filter, like \"[YuriVonFluri],bad\"\n";
	cin >> sterms;
	cout << "\nProcessing... This may take up to a minute depending on the log size...\n";
	char delimiter = ',';
	std::stringstream ss(sterms);
	std::string item;
	std::vector<std::string> searchTerms;
	while (std::getline(ss, item, delimiter))
	{
		searchTerms.push_back(item);
	}
	outfile << "###### This file was generated by ComwpODG's Log Filter v 0.01a ######\n\n";
	string line;
	bool preserve = false;
	while (!infile.eof())
	{
		getline(infile, line);
		preserve = false;
		for (unsigned int i = 0; i < searchTerms.size(); i++)
		{
			if (line.find(searchTerms[i]) != -1)
			{
				preserve = true;
			}
		}
		if (preserve)
		{
			outfile << line << "\n";
		}
	}
	cout << "Success!\nThank you for using ComwpODG's log filter.\n";
	system("pause");
}